version: '3.6'
services:
  jwt-auth:
    container_name: jwt-auth 
    build: .
    depends_on:
      - mongo
      - postgres
    networks:
      - auth-network
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    command: npm run start:watch
  mongo:
    container_name: mongo
    image: mongo:latest
    env_file:
    - .env
    ports:
      - 27017:27017
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - mongo_db:/data/db
#      - ./data/db:/data/db
  postgres:
    container_name: postgres
    build: ./postgres
    env_file:
      - .env
    networks:
      - auth-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
networks:
  auth-network:
    name: auth-network
volumes:
  postgres_data:
  mongo_db:

